grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.127.0.0.1.nip.io
  
  persistence:
    enabled: false

  initChownData:
    enabled: false

  podSecurityContext:
    fsGroup: 472
    runAsGroup: 472
    runAsUser: 472
  
  securityContext:
    runAsNonRoot: true
    runAsUser: 472
    runAsGroup: 472

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus.istio-system.svc.cluster.local:9090
          access: proxy
          isDefault: true

  # Importar Dashboards automáticamente
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'ingress-nginx'
          orgId: 1
          folder: 'Ingress'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/ingress-nginx
        - name: 'cluster'
          orgId: 1
          folder: 'Cluster'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/cluster

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      extraLabels:
        grafana_dashboard: "1"
