apiVersion: ENC[AES256_GCM,data:yc8=,iv:+TaeiHCsy8NMuYmZyWJk/Ta8Rw9Hqp4BuYsB1/0thQQ=,tag:Uz6QtXcUK3IYL3o+QfKIBQ==,type:str]
kind: ENC[AES256_GCM,data:awavSc9E,iv:Kzf/m4QeKthi4oJN8mfsokjlNic/7b38sPdx4fhriOQ=,tag:lSN2bOfcQKeQFNCeS4YKeg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QFNUD5Vy/4Va/vZBG7ttcUyklfJLc6GPPQ==,iv:EpE6l/UL+MnpNfwVB0u/TSrZJ1F4DiUwEDTpVAziHTI=,tag:DyvkzBASY8j1wwbLFPAgEw==,type:str]
    namespace: ENC[AES256_GCM,data:Qxb3HBfGzUZ26w==,iv:yGIJpy8o8OlgskTY3B9yPvVpFw4XrssGV3wr8Jo3i7A=,tag:+FfjAtvYy/NvHmosIQFcZg==,type:str]
type: ENC[AES256_GCM,data:sIyd4zgM,iv:GjrXzOAwTd58cQqoZsUbc5KTLsGLJSGu6DwwjPe8/RI=,tag:H9j6ZrY4lrM2x0jjsxECyQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:rucsD3s=,iv:Syk+P4BSr6qyA/Owje9wzCVoVecCUKU5A2RCRT5UXFg=,tag:PWKQ73P13K+oCauhRkq3GQ==,type:str]
    admin-password: ENC[AES256_GCM,data:p0nDjwSq4OVVrgUgFOVXP2y4qmyyYia2hw==,iv:GPJELLTi8D2cWzR/PBCTut9e2SxoL7HwwnDBp9+0Puw=,tag:/0WT8Q9DeSuj27Jn5m5iCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pk56zq9vvp5ufshdflyag2h8zddq42tq0wylxmv07tachfpu9uwsa57c67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b2RvOXN6bFo3Zkt0bVFF
            eU9vS3E0OS9qQzFvcVFJckZibVFxNUZ2bGc4CkUxT0lBNVBtdmh0VEs1cm5hQmh0
            SlZqZlNyZERLdEN3NnFic3dkSlE2N1kKLS0tIGpWVEJCUk9Bem8ydktwNDJRNkRu
            ZTJNN1FQYlMzU0NreVB3dUxvbGpBYjgKujpVpL1cwo58irwMyDWMJt2ZHtLcqlFE
            H3a/k3G6KdhgF/7CNUH22vlp0W+eGoSyAs9aQLH2TqYOBNuF3Y11EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T07:38:49Z"
    mac: ENC[AES256_GCM,data:R2fXKqDMvNV4QLceA0oB+mwmrotjSEdRUOe6BWfBjycVqNHmHnOcveqdWKGG4lNNO/lgFCGop+91MlPD0dTnVhbkip0uApUpMSIHYM8nfXzkLEAgZUthcZah9tXdjXhgh3FaNFVN/wGm+Ql6/bfqHg//xF4tw0zytfCoatWgLvk=,iv:+uToPrBzwxdgsdh0hnidasf9uzCGhdG/wXcpJzEvBzM=,tag:H7YNVMni5KJxOWwEOJd5Pg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
