apiVersion: ENC[AES256_GCM,data:R3w=,iv:imKx0Y/rNG+AvoRjJMfP66mA4hmoJkJNEVFmN4Wd8bc=,tag:qG15nfZfeILNknWeV4zWyA==,type:str]
kind: ENC[AES256_GCM,data:Z1PO5plU,iv:euOP5oafF+m2Q+47c7J6W3uAy4IDS6ApAp9iU4LNvOM=,tag:5/kzr1BhC92XEEnIompAaw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lbuwhEGkGHdgz5BdPJ779ehbBJtC3gAXbg==,iv:SnF32o5EnLSxm8gc+ZBdJJRyoOVDmcBe0vpnewguDnA=,tag:pwM+7BUahqFxu5yApLymFw==,type:str]
    namespace: ENC[AES256_GCM,data:x21zSJVbqAuJHw==,iv:vQ4foNa1Ys3WhFKgh2QMpo/ow/rrh20gF6B8jAmT8Kw=,tag:Jw5uaJ1+jQaOQVTSM9A5Lg==,type:str]
type: ENC[AES256_GCM,data:pI90ACRS,iv:hktWvDOMYh1hvBtNAnOc0gygPB8fd6Uhoe7KDwuj/Vs=,tag:rxCGqbhPbo+8SMwnykIsvQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:YLQFelk=,iv:RffiJUWjoByEIQ5qaOr8yX+UR0I+q1IoUIEl6pSrrAw=,tag:J/xyvWkcNhyiJqk+w3YyPQ==,type:str]
    admin-password: ENC[AES256_GCM,data:a3DNM7OhtIRM6aPn2a0Jv3kWzKE+xyL7/A==,iv:vFibUf8aXiv4bU1hvpsfPhRH92KQaP6oxzfvtsOJRw0=,tag:aR622cqsgH4IV5AsLAFD+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pk56zq9vvp5ufshdflyag2h8zddq42tq0wylxmv07tachfpu9uwsa57c67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT2orVG1NM3ZGUHFOekY3
            ei9kdERNTlpKRVNSTUVjZHRMMGhnUHVaeTE0CkNBdXZzVFl4NC9idzJ2Q0kvNFBG
            UTcvMEVnREJicjV5RkJoR2tvbjFLMzQKLS0tIFg2ckdtSG9ORzExQ1g5RmpyUHJr
            Z1JXeTVTYmVmMDQ5ZEdKWGlrdVBPKzQKICV/fj8EAHCKPeTuDIbn6vggA/FnLXma
            t9G4ksBXqxBFsqj2x4DPALDiPyooCnvBzWoSURdcgh8/NETmPCVbcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T07:44:10Z"
    mac: ENC[AES256_GCM,data:f8s8tTel68xYtm2meYnZrL+Fi8YGjWFqIVkUqOoD1yOs+jNKQ1WU2LDzKbwZdM+UztAGqJnDubkg49zQVWN8k/Ku8nenQibA49cTvSnHKdVm0WlMPiicyahMc+JJoV0FTHjLKvJMoy5EPXc2QfHSPNTEiAEJJrRRT7sYqiJi35U=,iv:0NOTA2Xeny0A/JmXc2E+Ee+vpeDSW63lCREwbTgQyzM=,tag:tOGVKfzddHwicQDybMVkKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
