apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    chart: loki-stack
    helm:
      values: |
        loki:
          persistence:
            enabled: true
            size: 2Gi
          config:
            limits_config:
              ingestion_rate_mb: 10
              ingestion_burst_size_mb: 20
              max_label_value_length: 2048
        promtail:
          enabled: true
          config:
            lokiAddress: http://{{ .Release.Name }}:3100/loki/api/v1/push
        grafana:
          enabled: false
          sidecar:
            datasources:
              enabled: true
              label: grafana_datasource
              labelValue: "1"
              isDefaultDatasource: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
