apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acid0ikario/k8s-workloads.git
    targetRevision: main
    path: deployments/production/demo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
