apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/acid0ikario/k8s-workloads.git
    targetRevision: master
    path: workloads/microservices-demo
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/acid0ikario/k8s-workloads.git
    targetRevision: master
    path: workloads/bookinfo
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garmindashboard
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/acid0ikario/k8s-workloads.git
    targetRevision: master
    path: workloads/garmindashboard
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: garmindashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/acid0ikario/k8s-workloads.git
    targetRevision: master
    path: workloads/registry
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: container-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
